"""
app.py
======
ML-Bot — Streamlit chatbot frontend for the Advanced RAG pipeline.

Run locally:
    streamlit run app.py

Run on Colab (Cloudflare tunnel):
    See README.md → Deployment section.

Dependencies loaded from disk (generated by build_index.py):
    all_embeddings_results.pkl
    chunk_sets.pkl
    {chunk_type}_{model_name}_faiss_index.bin  (6 files)
"""

from __future__ import annotations

import time

import numpy as np
import streamlit as st
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from embedding import (
    load_embedding_models,
    load_embeddings,
    load_chunk_sets,
    load_faiss_index,
    load_reranker,
    mmr_search,
    rerank_documents,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LLM_MODEL_ID    = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
BOT_NAME        = "ML Bot"
AVG_THRESHOLD   = 0.05          # minimum avg rerank score before hallucination guard fires
DEVICE          = "cuda" if torch.cuda.is_available() else "cpu"

# RAG defaults (override via sidebar in future iterations)
DEFAULT_EMBED_MODEL = "minilm"
DEFAULT_CHUNK_TYPE  = "hybrid"
DEFAULT_K           = 5
DEFAULT_LAMBDA      = 0.7
DEFAULT_FETCH_K     = 20


# ---------------------------------------------------------------------------
# Cached resource loaders  (run once per Streamlit session)
# ---------------------------------------------------------------------------

@st.cache_resource(show_spinner="Loading reranker …")
def _load_reranker():
    return load_reranker(device=DEVICE)


@st.cache_resource(show_spinner="Loading LLM …")
def _load_llm(model_id: str):
    quant_cfg = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16,
        quantization_config=quant_cfg,
        low_cpu_mem_usage=True,
    )
    model.to(DEVICE)
    return tokenizer, model


@st.cache_resource(show_spinner="Loading embedding models …")
def _load_embedding_models():
    return load_embedding_models(device=DEVICE)


@st.cache_resource(show_spinner="Loading embeddings store …")
def _load_embeddings_store():
    return load_embeddings("all_embeddings_results.pkl")


@st.cache_resource(show_spinner="Loading chunk sets …")
def _load_chunk_sets():
    return load_chunk_sets("chunk_sets.pkl")


@st.cache_resource(show_spinner="Loading FAISS index …")
def _load_faiss(chunk_type: str, model_name: str):
    return load_faiss_index(chunk_type, model_name)


# ---------------------------------------------------------------------------
# Boot — load everything before the first render
# ---------------------------------------------------------------------------

reranker                = _load_reranker()
tokenizer, llm_model    = _load_llm(LLM_MODEL_ID)
loaded_models           = _load_embedding_models()
all_embeddings_results  = _load_embeddings_store()
chunk_sets              = _load_chunk_sets()


# ---------------------------------------------------------------------------
# RAG pipeline
# ---------------------------------------------------------------------------

def _build_prompt(
    bot_name: str,
    conversation_history: str,
    context_string: str,
    current_question: str,
) -> str:
    return f"""You are an enterprise-grade Retrieval Augmented Generation (RAG) assistant named {bot_name}.

STRICT RULES:
1. Answer ONLY from the retrieved context below.
2. Never use outside knowledge or hallucinate facts.
3. Every factual statement must end with a citation in the format [1], [2], etc.
   Example: Overfitting occurs when a model memorises training data [1].
4. If the answer is not found in the context, respond EXACTLY with:
   "The requested information is not available in the provided context."

Conversation History:
{conversation_history}

Retrieved Context:
{context_string}

Current User Question:
{current_question}

Answer:"""


def ask_query(
    user_input_with_history: str,
    embedding_model_name: str = DEFAULT_EMBED_MODEL,
    chunk_type: str            = DEFAULT_CHUNK_TYPE,
    k_retrieval: int           = DEFAULT_K,
    lambda_mult: float         = DEFAULT_LAMBDA,
    fetch_k: int               = DEFAULT_FETCH_K,
) -> dict:
    """
    Full RAG pipeline: embed → MMR retrieve → rerank → hallucination filter → generate.

    Args:
        user_input_with_history: Structured string containing conversation
            history and the current question (see caller for format).
        embedding_model_name: Key into *loaded_models*.
        chunk_type:           ``"hybrid"`` or ``"recursive"``.
        k_retrieval:          Final number of chunks sent to the LLM.
        lambda_mult:          MMR diversity weight (0 = max diversity, 1 = max relevance).
        fetch_k:              Initial FAISS candidate pool size for MMR.

    Returns:
        Dict with keys: ``answer``, ``sources``, ``avg_rerank_score``,
        ``response_time_seconds``.
    """
    t0 = time.time()

    # ── Parse history / current question ──────────────────────────────────
    parts = user_input_with_history.split("Current Question:\n")
    history_str      = parts[0].replace("Previous Conversation:\n", "").strip()
    current_question = parts[1].strip()

    # ── Validate inputs ────────────────────────────────────────────────────
    if embedding_model_name not in loaded_models:
        return {"answer": f"Unknown embedding model: {embedding_model_name}",
                "sources": [], "avg_rerank_score": 0.0, "response_time_seconds": 0.0}

    if chunk_type not in all_embeddings_results:
        return {"answer": f"Unknown chunk type: {chunk_type}",
                "sources": [], "avg_rerank_score": 0.0, "response_time_seconds": 0.0}

    # ── Load data ──────────────────────────────────────────────────────────
    embed_model      = loaded_models[embedding_model_name]
    data             = all_embeddings_results[chunk_type][embedding_model_name]
    doc_embeddings   = data["embeddings"]
    doc_texts        = data["texts"]
    original_chunks  = chunk_sets.get(chunk_type, [{}] * len(doc_texts))
    faiss_idx        = _load_faiss(chunk_type, embedding_model_name)

    # ── Step 1: embed query ────────────────────────────────────────────────
    query_vec = embed_model.encode(
        [current_question],
        normalize_embeddings=True,
    ).astype(np.float32)

    # ── Step 2: MMR retrieval ──────────────────────────────────────────────
    candidates = mmr_search(
        query_embedding     = query_vec,
        document_embeddings = doc_embeddings,
        document_texts      = doc_texts,
        faiss_index         = faiss_idx,
        k                   = fetch_k,
        lambda_mult         = lambda_mult,
        fetch_k             = fetch_k,
    )

    # Attach metadata from original chunk objects
    for item in candidates:
        idx = item["index"]
        item["metadata"] = original_chunks[idx] if idx < len(original_chunks) else {}

    # ── Step 3: rerank ─────────────────────────────────────────────────────
    ranked = rerank_documents(
        query            = current_question,
        retrieved_chunks = candidates,
        reranker         = reranker,
        top_k            = k_retrieval,
    )

    # ── Step 4: hallucination guard ────────────────────────────────────────
    avg_score = float(np.mean([c["rerank_score"] for c in ranked])) if ranked else 0.0

    if avg_score < AVG_THRESHOLD:
        return {
            "answer":               "The requested information is not available in the provided context.",
            "sources":              [],
            "avg_rerank_score":     round(avg_score, 4),
            "response_time_seconds": round(time.time() - t0, 2),
        }

    # ── Step 5: build context & source list ───────────────────────────────
    context_parts: list[str] = []
    sources:       list[dict] = []

    for cid, chunk in enumerate(ranked, start=1):
        pg  = chunk["metadata"].get("page_number", "N/A")
        cid_str = chunk["metadata"].get("chunk_id",   "N/A")

        context_parts.append(
            f"[{cid}]\nPage: {pg}  Chunk: {cid_str}\n\n{chunk['text']}"
        )
        sources.append(
            {
                "citation":     f"[{cid}]",
                "page_number":  pg,
                "chunk_id":     cid_str,
                "rerank_score": round(chunk["rerank_score"], 4),
                "text":         chunk["text"],
            }
        )

    context_string = "\n\n".join(context_parts)

    # ── Step 6: generate ──────────────────────────────────────────────────
    prompt = _build_prompt(BOT_NAME, history_str, context_string, current_question)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=2048,
    ).to(llm_model.device)

    with torch.no_grad():
        tokens = llm_model.generate(
            **inputs,
            max_new_tokens    = 150,
            temperature       = 0.0,
            do_sample         = False,
            repetition_penalty = 1.1,
            pad_token_id      = tokenizer.eos_token_id,
        )

    answer = tokenizer.decode(
        tokens[0][len(inputs["input_ids"][0]):],
        skip_special_tokens=True,
    ).strip()

    return {
        "answer":               answer,
        "sources":              sources,
        "avg_rerank_score":     round(avg_score, 4),
        "response_time_seconds": round(time.time() - t0, 2),
    }


# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------

st.set_page_config(page_title="ML Bot", page_icon="🤖", layout="wide")

st.markdown(
    """
    <style>
        .block-container { padding-top: 1.2rem; max-width: 1000px; }
        .bot-title  { text-align: center; font-size: 34px; font-weight: 700; margin-bottom: 20px; }
        .bot-footer { text-align: center; color: gray; font-size: 12px; margin-top: 20px; }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown("<div class='bot-title'>🤖 ML Bot</div>", unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------

if "messages"  not in st.session_state: st.session_state.messages  = []
if "chat_id"   not in st.session_state: st.session_state.chat_id   = 1
if "all_chats" not in st.session_state: st.session_state.all_chats = {}


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

with st.sidebar:
    st.title("🤖 ML Bot")
    st.caption(f"Chat #{st.session_state.chat_id}")
    st.divider()

    st.markdown("### Pipeline")
    st.write("✅ Embedding : MiniLM")
    st.write("✅ Chunking  : Hybrid")
    st.write("✅ Retrieval : MMR + Reranker")
    st.write("✅ LLM       : TinyLlama 1.1B (4-bit)")
    st.divider()

    if st.button("➕ New Chat", use_container_width=True, type="primary"):
        if st.session_state.messages:
            st.session_state.all_chats[st.session_state.chat_id] = (
                st.session_state.messages.copy()
            )
        st.session_state.chat_id  += 1
        st.session_state.messages  = []
        st.rerun()

    if st.button("🗑  Clear Chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

    st.divider()
    st.markdown("### History")

    if not st.session_state.all_chats:
        st.caption("No previous chats yet.")
    else:
        for num in sorted(st.session_state.all_chats, reverse=True):
            if st.button(f"💬 Chat #{num}", key=f"hist_{num}", use_container_width=True):
                st.session_state.chat_id  = num
                st.session_state.messages = st.session_state.all_chats[num]
                st.rerun()

    st.divider()
    st.caption("📚 Machine Learning Book Assistant")


# ---------------------------------------------------------------------------
# Chat history display
# ---------------------------------------------------------------------------

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])


# ---------------------------------------------------------------------------
# Input + response
# ---------------------------------------------------------------------------

query = st.chat_input("Ask anything about Machine Learning …")

if query:
    # Store and display user message
    st.session_state.messages.append({"role": "user", "content": query})
    with st.chat_message("user"):
        st.markdown(query)

    # Build conversation history string (last 10 turns)
    recent = st.session_state.messages[-10:]
    history = "".join(
        f"{'User' if m['role'] == 'user' else 'Assistant'}: {m['content']}\n"
        for m in recent
    )

    enhanced_query = (
        f"Previous Conversation:\n{history}\n"
        f"Current Question:\n{query}\n"
    )

    # Generate and display assistant response
    with st.chat_message("assistant"):
        with st.spinner("Thinking …"):
            result = ask_query(
                user_input_with_history = enhanced_query,
                embedding_model_name    = DEFAULT_EMBED_MODEL,
                chunk_type              = DEFAULT_CHUNK_TYPE,
                k_retrieval             = DEFAULT_K,
                lambda_mult             = DEFAULT_LAMBDA,
                fetch_k                 = DEFAULT_FETCH_K,
            )

        answer = result["answer"]
        st.markdown(answer)

        # Sources
        if result.get("sources"):
            with st.expander("📚 Sources"):
                for src in result["sources"]:
                    label = (
                        f"{src['citation']}  "
                        f"Page {src['page_number']} · Chunk {src['chunk_id']} · "
                        f"Score {src['rerank_score']:.4f}"
                    )
                    with st.expander(label):
                        st.markdown(src["text"])

        # Metrics
        c1, c2 = st.columns(2)
        c1.metric("Avg Rerank Score",  result.get("avg_rerank_score", 0))
        c2.metric("Response Time",     f"{result.get('response_time_seconds', 0)} s")

    # Persist assistant message
    st.session_state.messages.append({"role": "assistant", "content": answer})
    st.session_state.all_chats[st.session_state.chat_id] = st.session_state.messages.copy()


# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------

st.markdown("<div class='bot-footer'>ML Bot · Powered by TinyLlama + FAISS + Streamlit</div>",
            unsafe_allow_html=True)
